[workspace]

members = [
    "entity",
    "migration",
    "gpuproxy",
]

# sqlx/sqlx-core/rsa/num-bigint-dig use spin_no_std features ,this features break build in rust-gpu-tools build
[patch.crates-io]
lazy_static = { git = "ssh://git@github.com/qy3u/lazy-static.rs.git" }
