[workspace]

members = [
    "entity",
    "migration",
    "gpuproxy",
]

[patch.crates-io]
# fix create index error, remove this if sea orm fix this issue https://github.com/SeaQL/sea-orm/issues/682
sea-query = { git = "https://github.com/hunjixin/sea-query", branch = "feat/0.23.0_index" }
